### ISSUE TITLE
Patch geht nicht mehr unter v3.69.7

### ISSUE THREAD

**Issue by Real-Slice** [jp112sdl/HM-WebUI-CC-Mod#3]
Hallo jp112sdl,
ich habe soeben auf die neue FW v3.69.7 aktualisiert und wollte Deinen Patch anwenden, allerdings bekomme ich folgenden Fehler nach Eingabe der Befehle:
```
mount -o remount,rw /
cd /www/rega/esp/controls/ ; wget --no-check-certificate -q -O - https://raw.githubusercontent.com/jp112sdl/HM-WebUI-CC-Mod/master/patch/heating_control.patch
 | patch heating_control.fn
patching file heating_control.fn
cd /www/webui/ ; wget --no-check-certificate -q -O - https://raw.githubusercontent.com/jp112sdl/HM-WebUI-CC-Mod/master/patch/webui_cc_add_batvalve.patch | patch webui.js
patching file webui.js
Possibly reversed hunk 1 at 49200
Hunk 1 FAILED 26862/26862.
     if (this.opts.stTemp) {
       this.showActualTemp();
     }
+    if (this.opts.stBat) {
+      this.showActualBat();
+    }
+    if (this.opts.stValve !== null) {
+      this.showActualValve();
+    }
     if (this.opts.idComfort && this.opts.idLowering) {
       this.showComfortEco();
     }
```
Vermutlich hat sich an der webui.js etwas geändert.

Grüße,
Slice

**Comment by jp112sdl** [comment]
Hmm, kann ich leider nix zu sagen.
Hab den Patch gerade mal auf dem Mac gegen die webui.js der original CCU3 webui.js laufen lassen und das ging ohne Probleme.
Ich weiß jedoch nicht, wie sich das `patch` Tool des CCU3 Linux Grundsystems verhält.
Vielleicht ist der Zeilenversatz inzwischen zu groß.
Dann müssten evlt. die Zeilennummern angepasst werden.
https://github.com/jp112sdl/HM-WebUI-CC-Mod/blob/c91326f1ace0a50e0913b8ac88a0d43e38e56978/patch/webui_cc_add_batvalve.patch#L3
https://github.com/jp112sdl/HM-WebUI-CC-Mod/blob/c91326f1ace0a50e0913b8ac88a0d43e38e56978/patch/webui_cc_add_batvalve.patch#L16

Kannst du das testen?

**Comment by Real-Slice** [comment]
Hab ich mir jetzt mal angeschaut übers Notepad++.
Meine piVCCU webui.js hat die folgenden Zeilennummern:

> ..Dann müssten evlt. die Zeilennummern angepasst werden.
> 
> https://github.com/jp112sdl/HM-WebUI-CC-Mod/blob/c91326f1ace0a50e0913b8ac88a0d43e38e56978/patch/webui_cc_add_batvalve.patch#L3

Zeile 35371

> https://github.com/jp112sdl/HM-WebUI-CC-Mod/blob/c91326f1ace0a50e0913b8ac88a0d43e38e56978/patch/webui_cc_add_batvalve.patch#L16

 Zeile 35570

Habe die Einträge von Hand reinkopiert und die Anzeigen sind wieder da.
